################
# GitLabCI template for Drupal projects.
#
# This template is designed to give any Contrib maintainer everything they need to test, without requiring modification.
# It is also designed to keep up to date with Core Development automatically through the use of include files that can be centrally maintained.
# As long as you include the project, ref and three files below, any future updates added by the Drupal Association will be used in your
# pipelines automatically. However, you can modify this template if you have additional needs for your project.
# The full documentation is on https://project.pages.drupalcode.org/gitlab_templates/
################

# For information on alternative values for 'ref' see https://project.pages.drupalcode.org/gitlab_templates/info/templates-version/
# To test a Drupal 7 project, change the first include filename from .main.yml to .main-d7.yml
include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'
#
################
# Pipeline configuration variables are defined with default values and descriptions in the file
# https://git.drupalcode.org/project/gitlab_templates/-/blob/main/includes/include.drupalci.variables.yml
# Uncomment the lines below if you want to override any of the variables. The following is just an example.
################
variables:
  SKIP_ESLINT: '1'
  SKIP_STYLELINT: '1'
  OPT_IN_TEST_NEXT_MINOR: '1'
  OPT_IN_TEST_NEXT_MAJOR: '1'
  # Don't install JavaScript dependencies; they're not used in this CI process right now.
  _COMPOSER_YARN_INSTALL: '0'
  # @see https://project.pages.drupalcode.org/gitlab_templates/jobs/cspell
  _CSPELL_DICTIONARY: 'dictionary.txt'
  _CSPELL_IGNORE_PATHS: 'build/css/*, pnpm-lock.yaml'

stages:
  - build
  - validate
  - test
  - deploy

push to bitbucket:
  stage: deploy
  # We don't need any artifacts from previous stages.
  # @see https://docs.gitlab.com/ee/ci/jobs/job_artifacts.html#prevent-a-job-from-fetching-artifacts
  dependencies: []
  before_script:
    - apt-get update -y
    - apt-get install -y openssh-client
  script:
    # We need to identify ourselves to Git in order to push.
    - git config --global user.name "Mediacurrent"
    - git config --global user.email "mediacurrent@users.noreply.drupalcode.org"
    # Ensure we can push to the remote.
    - eval "$(ssh-agent -s)"
    - ssh-add - < "${SSH_PRIVATE_KEY}"
    - mkdir ~/.ssh
    - cp $SSH_KNOWN_HOSTS ~/.ssh/known_hosts
    # Test that we can connect successfully.
    - ssh -T git@bitbucket.org
    # Update the `origin` remote to push to BitBucket.
    - git remote set-url origin git@bitbucket.org:mediacurrent/xb-drupal-theme.git
    - git remote -v
    - git push --set-upstream origin HEAD
  rules:
    # Deploy when we push to the release branch (not in a fork).
    - if: $CI_COMMIT_BRANCH == "1.x" && $CI_PIPELINE_SOURCE == "push" && $CI_PROJECT_ROOT_NAMESPACE == "project"
      when: on_success
