<?php

/**
 * @file
 * Functions to support theming.
 */

/**
 * Implements hook_preprocess_image_widget().
 */
function mercury_preprocess_image_widget(array &$variables): void {
  $data = &$variables['data'];

  // This prevents image widget templates from rendering preview container HTML
  // to users that do not have permission to access these previews.
  // @todo revisit in https://drupal.org/node/953034
  // @todo revisit in https://drupal.org/node/3114318
  if (isset($data['preview']['#access']) && $data['preview']['#access'] === FALSE) {
    unset($data['preview']);
  }
}

/**
 * Implements template_preprocess_html().
 */
function mercury_preprocess_html(array &$variables): void {
  $variables['dark_mode'] = theme_get_setting('dark_mode');
}

/**
 * Implements hook_form_system_theme_settings_alter().
 */
function mercury_form_system_theme_settings_alter(array &$form): void {
  $form['dark_mode'] = [
    '#type' => 'checkbox',
    '#title' => t('Enable dark mode'),
    '#default_value' => theme_get_setting('dark_mode'),
  ];
}
