sommertheater.settings:
  type: theme_settings
  label: "Sommertheater settings"
  mapping:
    scheme:
      type: string
      label: Color scheme
      constraints:
        Choice:
          # @see \Drupal\sommertheater\Hook\ThemeHooks::themeSettingsFormAlter()
          - light
          - dark
