mercury.settings:
  type: theme_settings
  label: "Mercury settings"
  mapping:
    scheme:
      type: string
      label: Color scheme
      constraints:
        Choice:
          # @see \Drupal\mercury\Hook\ThemeHooks::themeSettingsFormAlter()
          - light
          - dark
